# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy React Demo

on:
  push:
    branches: [ master ]
    paths:
      - "react-demo/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14
    - working-directory: ./react-demo
      run: npm ci
    - working-directory: ./react-demo
      run: npm run build
    - name: Create Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        path: ./react-demo/build
        retention-days: 1
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.8
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: owo
          restore-keys: owo
      - run: npm install -g @lhci/cli@0.7.x
      - continue-on-error: true
        run: lhci autorun --staticDistDir=./ --url=http:localhost --numberOfRuns=1
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.8
      - name: SCP Files
        # You may pin to the exact commit or the version.
        # uses: appleboy/scp-action@b476d5806f2a4c1ed5902a87fa91b0623cac7258
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          source: "artifact/*"
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          overwrite: true
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: echo "uwu"
      
